# Site
title:              Clynie's Blog Site
bio:                'Life, Anime, Japan, IT, and other interesting things'
description:        "Han Yihong's blog site"
reading_time:       false
words_per_minute:   200
